// svelte/src/lib/components/Checkbox.svelte
<script lang="ts">
  type CheckboxProps = {
        label?: string;
        checked: boolean;
        onChange: (checked: boolean) => void;
    };

    let {
        label,
        checked,
        onChange
    } = $props<CheckboxProps>();

  const toggle = () => {
    onChange(!checked);
  };
</script>

{#if label}
  <label for="checkboxInput">{label}</label>
{/if}
<input
  id="checkboxInput"
  class="checkbox"
  type="checkbox"
  {checked}
  on:change={toggle}
/>

// react/app/common/Checkbox.tsx
import { FC, Fragment } from "react";

type CheckboxProps = {
    label?: string;
    checked: boolean;
    onChange: (checked: boolean) => void;
}

export const Checkbox: FC<CheckboxProps> = ({label, checked, onChange}) => {
    const toggle = () => {
        onChange(!checked);
    }

    return (
        <Fragment>
            {label && <label>{label}</label>}
            <input className="checkbox" type="checkbox" checked={checked} onChange={toggle} />
        </Fragment>
    )
}
