// vue/components/Checkbox.vue
<script setup lang="ts">
    type CheckboxProps = {
        label?: string;
        checked: boolean;
        onChange: (checked: boolean) => void;
    };

    const {
        label,
        checked,
        onChange
    } = defineProps<CheckboxProps>();

    const toggle = () => {
        onChange(!checked);
    }
</script>
<template>
    <label v-if="label">{{ label }}</label>
    <input class="checkbox" type="checkbox" :checked="checked" @change="toggle" />
</template>

// svelte/src/lib/components/Checkbox.svelte
<script lang="ts">
  type CheckboxProps = {
        label?: string;
        checked: boolean;
        onChange: (checked: boolean) => void;
    };

    let {
        label,
        checked,
        onChange
    } = $props<CheckboxProps>();

  const toggle = () => {
    onChange(!checked);
  };
</script>

{#if label}
  <label for="checkboxInput">{label}</label>
{/if}
<input
  id="checkboxInput"
  class="checkbox"
  type="checkbox"
  {checked}
  on:change={toggle}
/>
