// angular/src/app/common/input/input.component.ts

import { Component, Input, OnInit } from '@angular/core';
import { ControlValueAccessor, FormsModule, NG_VALUE_ACCESSOR } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';

type InputTypes = "text" | "password" | "date" | "number" | "datetime-local" | "email";

@Component({
  selector: 'app-input',
  standalone: true,
  templateUrl: './input.component.html',
  styleUrls: ['./input.component.scss'],
  imports: [TranslateModule, FormsModule ],
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: InputComponent,
    multi: true
  }]
})
export class InputComponent implements ControlValueAccessor, OnInit {

  @Input() type: InputTypes = 'text';
  @Input() label: string | undefined;
  @Input() disabled: boolean = false;
  @Input() required: boolean = false;
  @Input() minLength?: number;
  @Input() maxLength?: number;

  valid: boolean = true;

  writeValue(value: any): void {
    this.inputValue = value;
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  inputValue: any;
  onChange: any = () => {};
  onTouched: any = () => {};

  ngOnInit() {
    if (this.required) {
      this.onChange({ value: this.inputValue, valid: !!this.inputValue });
    }
  }

  validate(): void {
    let valid = true;

    if (this.required && !this.inputValue) {
      valid = false;
    }

    switch (this.type) {
      case 'number':
        if (isNaN(this.inputValue)) {
          valid = false;
        }
        break;
      case 'email':
        if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(this.inputValue)) {
          valid = false;
        }
        break;
      default:
        break;
    }

    if (this.minLength && this.inputValue.length < this.minLength) {
      valid = false;
    }

    if (this.maxLength && this.inputValue.length > this.maxLength) {
      valid = false;
    }
    this.valid = valid;
    this.onChange({ value: this.inputValue, valid: valid });
  }

  isMailValid(value: string): boolean {
    return !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
  }

  isNaN(value: number): boolean {
    return isNaN(value);
  }

  onInputChange(event: any) {
    this.inputValue = event.target.value;
    this.validate();
    this.onTouched();
  }
}

<div class="app-input" [class.disabled]="disabled">
    @if(label){
        <label for="inputField">{{ label }}</label>
    }
    
    <input id="inputField" type="{{ type }}" [(ngModel)]="inputValue" (change)="onInputChange($event)" [disabled]="disabled" [required]="required">
    @if(!valid && required){
        <div>{{ "input.required" | translate }}</div>
    }
    @if(!valid && (type === 'number' && isNaN(inputValue))){
        <div>{{ "input.invalid_number" | translate }}</div>
    }
    @if(!valid && type === 'email' && !isMailValid(inputValue)){
        <div>{{ "input.invalid_email" | translate }}</div>
    }
    @if(!valid && minLength && inputValue.length < minLength){
        <div>{{ "input.invalid_minlength" | translate: {value: minLength} }}</div>
    }
    @if(!valid && maxLength && inputValue.length > maxLength){
        <div>{{ "input.invalid_maxlength" | translate: {value: maxLength} }}</div>
    }
</div>

// svelte/src/lib/components/Input.svelte
<script lang="ts">
    type InputTypes = "text" | "password" | "date" | "number" | "datetime-local" | "email";
    type ErrorTypes = "required" | "number" | "email" | "minLength" | "maxLength";
    type InputProps = {
        id: string;
        label?: string;
        placeholder?: string;
        type: InputTypes;
        disabled?: boolean;
        required?: boolean;
        minLength?: number;
        maxLength?: number;
        value: string;
        onChange: (value: string) => void;
        className?: string;
    }
    
    let {
        id,
        label,
        placeholder,
        type,
        disabled,
        required,
        minLength,
        maxLength,
        value,
        onChange,
        className
    } = $props<InputProps>();
  
    let errors = $state<ErrorTypes[]>([]);
  
    function validate(event: FocusEvent) {
      const target = event.target as HTMLInputElement;
      const val = target.value;
      errors = [];
  
      if (required && val.trim() === '') {
        errors.push("required");
      }
      if (type === 'email' && !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(val)) {
        errors.push("email");
      }
      if (type === 'number' && isNaN(parseFloat(val))) {
        errors.push("number");
      }
      if (minLength && val.length < minLength) {
        errors.push("minLength");
      }
      if (maxLength && val.length > maxLength) {
        errors.push("maxLength");
      }
  
      onChange && onChange(val);
    }
  
    function handleChange(event: Event) {
      onChange((event.target as HTMLInputElement).value);
      errors = [];
    }
</script>
  
<div class="app-input {className}">
    {#if label}
    <label for={`inputField-${id}`}>{{ label }}</label>
    {/if}
    <input
    id={`inputField-${id}`}
    type={type}
    placeholder={placeholder}
    disabled={disabled}
    required={required}
    minLength={minLength}
    maxLength={maxLength}
    on:change={handleChange}
    on:blur={validate}
    bind:value={value}
    />
    {#each errors as error}
    <div>{error}</div>
    {/each}
</div>
