// react/app/common/Tasks.tsx
"use client";
import { Fragment, useEffect, useState } from "react";
import { languages, fallbackLng } from '../i18n/settings'
import { useTranslation } from '../i18n/client'
import Input from "./Input";
import { db } from "./db";
import TaskType from "@common/types/task";
import { getTasks } from "@common/types/db";
import { Task } from "./Task";

export default function Tasks({lng}: {lng: string}) {
    
    if (languages.indexOf(lng) < 0) lng = fallbackLng;
    const { t } = useTranslation(lng);
    const [task, setTask] = useState<string>('');
    const [tasks, setTasks] = useState<TaskType[]>([]);
    const [archivedTasks, setArchivedTasks] = useState<TaskType[]>([]);
    
    const add = async(): Promise<void> => {
        const entry = await db.tasks.add({
            description: task,
            created_at: new Date(),
            updated_at: new Date(),
        });
        if(entry){
            setTask("");
        }
    }

    const edit = async (task: TaskType): Promise<void> => {
        if(!task.id) return;
        await db.tasks.where("id").equals(task.id).modify({
        ...task
        });
    }

    const remove = async (id: string): Promise<void> => {
        await db.tasks.where("id").equals(id).delete();
    }

    useEffect(() => {
        getTasks(db).subscribe((tasks) => {
          setTasks(tasks.filter(({completed_at}) => !completed_at));
          setArchivedTasks(tasks.filter(({completed_at}) => !!completed_at));
        });
    }, []);

    return (
        <Fragment>
            <div className="tasks--header">
                <Input className="tasks--input" id="task--input" type="text" value={task} onChange={setTask} />
                <button onClick={add} className="pill-segment">
                    {t("task.add")}
                </button>
            </div>
            <ul className="tasks">
                {tasks.map(({id, description, created_at, updated_at,completed_at}) => 
                    (<li key={id}>
                        <Task
                            lng={lng}
                            id={id!}
                            description={description}
                            created_at={created_at}
                            updated_at={updated_at}
                            completed_at={completed_at}
                            onDelete={(taskId)=>remove(taskId)}
                            onChange={event => edit(event)}
                        />
                    </li>)
                )}
                {!tasks.length && <li>{ t("task.empty") }</li>}
            </ul>
            <h2 className="underlined">{t("task.archive")}</h2>
            <ul className="tasks">
                {archivedTasks.map(({id, description, created_at, updated_at,completed_at}) => 
                    (<li key={id}>
                        <Task
                            lng={lng}
                            id={id!}
                            description={description}
                            created_at={created_at}
                            updated_at={updated_at}
                            completed_at={completed_at}
                            onDelete={(taskId)=>remove(taskId)}
                            onChange={event => edit(event)}
                        />
                    </li>)
                )}
                {!archivedTasks.length && <li>{ t("task.empty_archive") }</li>}
            </ul>
        </Fragment>
    )
}

// angular/src/app/routes/tasks/tasks.component.ts
import { Component, OnInit } from '@angular/core';
import { TranslateModule } from '@ngx-translate/core';

import { TaskComponent } from '../../common/task/task.component';
import { InputComponent } from '../../common/input/input.component';

import { getTasks } from '../../../../../common/types/db';
import { db } from '../../common/db';
import { FormsModule } from '@angular/forms';
import { AsyncPipe } from '@angular/common';
import Task from '../../../../../common/types/task';

@Component({
  selector: 'app-tasks',
  standalone: true,
  imports: [TranslateModule, FormsModule, TaskComponent, InputComponent, AsyncPipe],
  templateUrl: './tasks.component.html',
  styleUrl: './tasks.component.scss',
  host: {ngSkipHydration: "true"}
})
export class TasksComponent implements OnInit {
  constructor() {}

  tasks: Task[] = [];
  archivedTasks: Task[] = [];
  newTask: string = "";

  ngOnInit(): void {
    getTasks(db).subscribe((tasks) => {
      this.tasks = tasks.filter(({completed_at}) => !completed_at);
      this.archivedTasks = tasks.filter(({completed_at}) => !!completed_at);
    });
  }

  async add(): Promise<void> {
    const entry = await db.tasks.add({
      description: this.newTask,
      created_at: new Date(),
      updated_at: new Date(),
    });
    if(entry){
      this.newTask = "";
    }
  }

  async edit(task: Task): Promise<void> {
    if(!task.id) return;
    await db.tasks.where("id").equals(task.id).modify({
      ...task
    });
  }

  async delete(id: string): Promise<void> {
    await db.tasks.where("id").equals(id).delete();
  }
}

<div class="tasks--header">
    <app-input class="tasks--input" placeholder="{{ 'task.placeholder' | translate }}" [(ngModel)]="newTask" />
    <button (click)="add()" class="pill-segment">{{ "task.add" | translate }}</button>
</div>
<ul class="tasks">
    @for (task of tasks; track task.id) {
        <li>
            <app-task 
                [id]="task.id"
                [description]="task.description"
                [created_at]="task.created_at"
                [updated_at]="task.updated_at"
                [completed_at]="task.completed_at"
                (delete)="delete(task.id!)"
                (change)="edit($event)"
            />
        </li>
    } @empty {
        <li>{{ "task.empty" | translate }}</li>
    }
</ul>

<h2 class="underlined">{{ "task.archive" | translate }}</h2>
<ul class="tasks">
    @for (task of archivedTasks; track task.id) {
        <li>
            <app-task 
                [id]="task.id"
                [description]="task.description"
                [created_at]="task.created_at"
                [updated_at]="task.updated_at"
                [completed_at]="task.completed_at"
                (delete)="delete(task.id!)"
                (change)="edit($event)"
            />
        </li>
    } @empty {
        <li>{{ "task.empty" | translate }}</li>
    }
</ul>
