// svelte/src/lib/components/Task.svelte
<script lang="ts">
    import type TaskType from "@/common/types/task";
    import { formatRelativeDate } from "@/common/utils/dateUtils";
    import Input from "./Input.svelte";
    import Checkbox from "./Checkbox.svelte";

    export let id: string;
    export let description: string;
    export let completed_at: Date | string | undefined;
    export let created_at: Date | string;
    export let updated_at: Date | string;
    export let onChange: (task: TaskType) => void;
    export let onDelete: (id: string) => void;

    let editing = $state<boolean>(false);
    let value = $state<string>(description);
    const complete = (checked: boolean): void => {
        const created = typeof created_at === "string" ? new Date(created_at) : created_at;
        const updated = typeof updated_at === "string" ? new Date(updated_at) : updated_at;
        onChange({ id, description, completed_at: checked ? new Date() : undefined, created_at: created, updated_at: updated });
    };

    const edit = (): void => {
        if(editing){
            const created = typeof created_at === "string" ? new Date(created_at) : created_at;
            const completed = typeof completed_at === "string" ? new Date(completed_at) : completed_at;
            onChange({ id, description: value, completed_at: completed, created_at: created, updated_at: new Date() });
        }
        editing  = !editing;
    };

    const onValueChange = (val: string) => {
        value = val;
    }

    const formatDate = (date: Date | string): string => {
        date = typeof date === "string" ? new Date(date) : date;
        return formatRelativeDate(date, "be-NL");
    };

    const formatTimestamp = (date: Date | string): string => {
        date = typeof date === "string" ? new Date(date) : date;
        return `${date.toLocaleDateString("be-NL")}, ${date.toLocaleTimeString("be-NL")}`;
    }
</script>
<div class="task--wrapper" id={id}>
    <div class="task { !!completed_at && 'complete' }">
        <Checkbox checked={!!completed_at} onChange={complete}/>
        <Input id={`task-${id}`} type="text" value={value} disabled={!editing}
        className="task--input" onChange={onValueChange} />
        <div class="task--controls">
            {#if !completed_at}
                <button class="pill-segment" onClick={edit}>{ $t(editing ? "task.save" : "task.edit") }</button>
            {/if}
            
            <button class="pill-segment" onClick={() => onDelete(id)}>{ $t("task.delete") }</button>
        </div>
    </div>
    <div class="task--meta">
        <div class="task--date" title={formatTimestamp(updated_at || created_at)}>
            <span>{ $t(updated_at !== created_at? "time.updated" : "time.created") }</span>
            <span>{ formatDate(updated_at || created_at) }</span>
        </div>
        {#if completed_at}
            <div class="task--date" title={formatTimestamp(completed_at)}>
                <span>{ $t("time.completed") }</span>
                <span>{ formatDate(completed_at) }</span>
            </div>
        {/if}
    </div>
</div>

// angular/src/app/common/task/task.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';

import { InputComponent } from '../input/input.component';
import { CheckboxComponent } from '../checkbox/checkbox.component';
import Task from "../../../../../common/types/task";
import { formatRelativeDate } from "../../../../../common/utils/dateUtils";
import { DatePipe } from '@angular/common';


@Component({
  selector: 'app-task',
  standalone: true,
  imports: [TranslateModule, FormsModule, ReactiveFormsModule, InputComponent, CheckboxComponent, DatePipe],
  templateUrl: './task.component.html',
  styleUrl: './task.component.scss'
})
export class TaskComponent implements Task {
  @Input() editable: boolean = false;
  @Input() id?: string = "";
  @Input() description: string = "";
  @Input() created_at: Date = new Date();
  @Input() updated_at: Date = new Date();
  @Input() completed_at?: Date;

  @Output() change = new EventEmitter<Task>();
  @Output() delete = new EventEmitter<Task>();

  complete(checked: boolean): void {
    this.completed_at = checked ? new Date() : undefined;
    this.emit();
  }

  edit(): void {
    if(this.editable){
      this.emit();
    }
    this.editable = !this.editable;
  }

  emit(): void {
    this.change.emit({
      id: this.id,
      description: this.description,
      created_at: this.created_at,
      updated_at: new Date(),
      completed_at: this.completed_at
    })
  }

  formatDate(date: Date): string {
    return formatRelativeDate(typeof date === "string" ? new Date(date) : date, "be-NL");
  }
}

<div class="task--wrapper" [id]="id">
  <div class="task" [class.complete]="!!completed_at">
    <app-checkbox [checked]="completed_at != null" (checkedChange)="complete($event)"/>
    <app-input type="text" [(ngModel)]="description" [disabled]="!editable" class="task--input" />
    <div class="task--controls">
      @if(!completed_at){
        <button (click)="edit()" [attr.disabled]="!!completed_at ? true : null" class="pill-segment">{{ (editable ? "task.save" : "task.edit") | translate }}</button>
      }
      <button (click)="delete.emit()" class="pill-segment">{{ "task.delete" | translate }}</button>
    </div>
  </div>
  <div class="task--meta">
    @if(updated_at){
      <div class="task--date" [title]="updated_at | date: 'yyyy-MM-dd, HH:mm'">
        <span>{{("time.updated" | translate) }}</span>
        <span>{{(formatDate(updated_at) | translate)}}</span>
      </div>
    } @else {
      <div class="task--date" [title]="created_at | date: 'yyyy-MM-dd, HH:mm'">
        <span>{{("time.created" | translate) }}</span>
        <span>{{(formatDate(created_at) | translate)}}</span>
      </div>
    }

    @if(completed_at){
      <div class="task--date" [title]="completed_at | date: 'yyyy-MM-dd, HH:mm'">
        <span>{{("time.completed" | translate) }}</span>
        <span>{{(formatDate(completed_at) | translate)}}</span>
      </div>
    }
  </div>
</div>
